### ISSUE TITLE
Question: USB Host RNDIS

### ISSUE THREAD

**Issue by SimonMerrett** [majbthrd/D21ecm#1]
Hi @majbthrd thanks for your brilliant contributions to TinyUSB's networking side of things.  I agree that TinyUSB is the way forward for development but I traced back your work to this repo and your stm32 version, noting that there is a newer version of lwip here and also you have implemented actions on button presses, which is better than the RNDIS example you ported to TinyUSB, in my view.

I spoke to Ha at TinyUSB about RNDIS on USB host and as expected, it's not high on his agenda (and I don't expect it to be high on yours). I'm pretty new to USB so it will take me some time to learn the ropes but it's a feature I'm interested in and would be happy to do so under TinyUSB for all to benefit from if I can get my contributions to the required standard. 

Finally getting to my question: do you think implementing an RNDIS host with TinyUSB/lwIP is feasible? From a naive perspective it all looks doable but I bow to your clear insight and experience in this area. Thanks!

**Comment by majbthrd** [comment]
@SimonMerrett , to be honest, I wasn't even aware that the lwip versions were slightly different; bringing TinyUSB's lwip usage from 2.1.0-stable to 2.1.2-stable should be easily remedied.

The "better" "actions on button presses" found in D21rndis/D21ecm/D21eem can be pasted into the TinyUSB example.  The only reason that I didn't put it in the TinyUSB example is because TinyUSB it is supposed to be "Tiny", and the embedded image and claptrap in D21rndis cause it to use more memory.  The goal of TinyUSB is to run on many microcontrollers, and a bloated example might run on fewer targets.  Furthermore, sticking with the base lwip example webserver puts TinyUSB on the same footing as any other port of lwip.

USB Host is substantially more difficult than USB Device, and that is just the USB stack; wanting to connect to a RNDIS device implies that the host wants to run some sort of networking application, which further adds to complexity and potentially substantial memory usage.  So, personally, I really don't see a good use case for an embedded microcontroller acting as USB host to a RNDIS network adapter.  Such usage is best left to small board computers running something like Linux, IMHO.

**Comment by SimonMerrett** [comment]
@majbthrd thanks for your reply. Sorry for being ambiguous - I think I was getting confused between the lwIP 1.4.1 in fetisov's lrndis repo vs 2.x in D21ecm. Understand the reasons for going with the simple webserver example in TinyUSB - I suppose I wanted to compliment you on the other example too.

Thanks too for your thoughts on RNDIS host. Personally I would only want one RNDIS device (that cannot enumerate as a CDC) attached to one RNDIS host, with a limited set of networking features (RNDIS host send UDP or multicast at low rates using fixed IP addresses). Niche, indeed. I acknowledge it's not as simple on a microcontroller as making a basic implementation on e.g. OpenWRT on a small Linux device. But that approach trades out the advantages of fast boot time and relatively low power that microcontrollers offer. Hope I've not been a bother and thanks for your contributions.

**Comment by majbthrd** [comment]
@SimonMerrett, no worries.  Consider that whatever power savings that might be seen with the microcontroller can be dwarfed by the power requirements of being a USB host.  A standard USB host must typically be able to supply 5V @ 0.5A, e.g. 2.5 watts to the device.  That doesn't mean that all RNDIS devices will consume that much, but one should be prepared for this.

There is a growing cornucopia of microcontrollers that have integrated network capability, particularly with wireless, that target "IoT" applications.  You could potentially spare yourself some complexity by generating Ethernet packets directly, rather than translating them back and forth into RNDIS protocol over USB.  It's just food for thought.
